name: Run Shell Script with Python 3.11

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Run Shell Script
        run: |
          chmod +x ./project/test.sh
          ./project/test.sh
