name: Continuous Integration Tests

on:
  push:
    branches:
    - main
    
    
jobs:
   testsh:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main

# Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

# Install dependencies
    - name: Install dependecies
      run: 
        python -m pip install --upgrade pip
        pip install ./data/requirements.txt
        
    - name: Set execute permissions
      run: 
        chmod +x ./project/tests.sh

# Run test.sh
    - name: Test script
      run: |
        ./project/test.sh
