name: Run project test 

on:
  push:
    branches:
    - main
    
    
jobs:
   testsh:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main

# Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

# Run test.sh
    - name: Test script
      run: 
        /project/test.sh
